In [ ]:
# IMPORTING STATEMENTS
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(7)

In [ ]:
from sklearn.preprocessing import StandardScaler

# Import the Data

In [ ]:
# training data
data = pd.read_csv('train.csv', index_col=0)
data = data.iloc[:1000,:]
data

,InterestRate,MinorityRatio,CensusTractMedFamIncome,MonthlyIncome,HUDMedIncome,LTV,PaymentCount,Age1,Age2,HousingExpense,...,State_31,State_39,State_42,State_48,State_55,State_infrequent_sklearn,Minority_Min,Minority_Missing,Minority_White,Borrower2Dummy
170846,3.750,5.631,96500,4693,69400,72.0,360,65,61,21.76,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1
154335,4.375,5.745,93258,3194,94200,79.0,360,34,0,30.74,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0
145818,2.750,21.300,82260,6344,81700,99.0,360,32,56,27.87,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
94035,3.375,4.000,71172,9776,76700,80.0,360,25,25,9.00,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
175348,4.250,8.000,65755,3800,73100,80.0,360,30,0,12.00,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222419,4.250,26.018,101591,4583,89900,80.0,360,47,0,30.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
49563,2.875,8.728,55395,5057,64900,72.0,240,54,46,16.82,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1
3738,2.625,5.727,75379,5000,71500,73.0,240,36,0,29.82,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0
20289,3.000,12.000,132868,9437,84700,72.0,300,25,51,14.00,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
115367,3.125,49.065,62875,5850,70600,75.0,360,61,57,20.72,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1

In [ ]:
# defining response variable and input features
y = data.pop('InterestRate')
X = data.copy()

In [ ]:
# test data
data_test = pd.read_csv('test.csv', index_col=0)
data_test = data_test.iloc[:200, :]
data_test.head()

,InterestRate,MinorityRatio,CensusTractMedFamIncome,MonthlyIncome,HUDMedIncome,LTV,PaymentCount,Age1,Age2,HousingExpense,...,State_31,State_39,State_42,State_48,State_55,State_infrequent_sklearn,Minority_Min,Minority_Missing,Minority_White,Borrower2Dummy
188315,4.000,47.950,80357,18334,95900,80.0,360,39,0,17.07,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0
104813,3.250,6.489,112882,10065,86200,72.0,360,64,66,20.14,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1
164647,3.475,9.661,118045,19272,82300,72.0,360,62,62,14.70,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1
110948,3.125,5.172,100096,5171,89200,80.0,180,43,0,25.31,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
152548,4.750,4.396,91638,14262,79600,80.0,360,39,31,12.66,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1

In [ ]:
y_test = data_test.pop('InterestRate')
X_test = data_test.copy()

# Scaling

In [ ]:
# input variables
ss = StandardScaler()
X_train = ss.fit_transform(X)
X_test = ss.transform(X_test)
X = pd.DataFrame(X_train, columns=data.columns)
X_test = pd.DataFrame(X_test, columns=data.columns)
X.describe()

,MinorityRatio,CensusTractMedFamIncome,MonthlyIncome,HUDMedIncome,LTV,PaymentCount,Age1,Age2,HousingExpense,DebtExpense,...,State_31,State_39,State_42,State_48,State_55,State_infrequent_sklearn,Minority_Min,Minority_Missing,Minority_White,Borrower2Dummy
count,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,...,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03
mean,-3.552714e-17,-1.136868e-16,-6.394885e-17,-4.973799e-16,9.539036e-16,-1.882938e-16,5.329071e-17,5.684342e-17,3.197442e-17,-2.735590e-16,...,-7.149836e-17,2.842171e-17,-2.842171e-17,4.618528e-17,-9.947598e-17,-6.039613e-17,-2.131628e-17,7.105427e-18,-7.105427e-18,3.907985e-17
std,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,...,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00
min,-9.253044e-01,-1.956165e+00,-1.404702e+00,-2.737299e+00,-8.765187e-01,-2.775092e+00,-1.822692e+00,-1.065152e+00,-2.303190e+00,-2.706364e+00,...,-2.145346e-01,-3.164017e-01,-2.342057e-01,-1.818182e-01,-3.622454e-01,-4.984370e-01,-2.195860e-01,-2.968826e-01,-2.621834e+00,-1.165543e+00
25%,-6.750907e-01,-6.671393e-01,-6.963080e-01,-6.609928e-01,-8.765187e-01,-1.093804e+00,-7.910492e-01,-1.065152e+00,-7.343797e-01,-7.116153e-01,...,-2.145346e-01,-3.164017e-01,-2.342057e-01,-1.818182e-01,-3.622454e-01,-4.984370e-01,-2.195860e-01,-2.968826e-01,3.814123e-01,-1.165543e+00
50%,-3.852332e-01,-2.180983e-01,-2.425924e-01,-6.425922e-02,-1.184703e-01,5.874840e-01,-1.278501e-01,1.349960e-01,-1.844101e-01,-3.423555e-03,...,-2.145346e-01,-3.164017e-01,-2.342057e-01,-1.818182e-01,-3.622454e-01,-4.984370e-01,-2.195860e-01,-2.968826e-01,3.814123e-01,8.579692e-01
75%,2.568813e-01,5.069799e-01,3.780499e-01,5.263436e-01,1.342125e-01,5.874840e-01,7.564154e-01,8.385313e-01,5.349657e-01,7.768093e-01,...,-2.145346e-01,-3.164017e-01,-2.342057e-01,-1.818182e-01,-3.622454e-01,-4.984370e-01,-2.195860e-01,-2.968826e-01,3.814123e-01,8.579692e-01
max,3.105861e+00,4.393888e+00,3.737260e+00,3.900341e+00,3.924454e+00,5.874840e-01,3.114457e+00,2.411140e+00,3.422982e+00,2.730064e+00,...,4.661252e+00,3.160540e+00,4.269750e+00,5.500000e+00,2.760560e+00,2.006272e+00,4.554024e+00,3.368335e+00,3.814123e-01,8.579692e-01

In [ ]:
# dependent variables
ss_y = StandardScaler()
y = ss_y.fit_transform(np.array(y).reshape(-1, 1))
y_test = ss_y.transform(np.array(y_test).reshape(-1, 1))
pd.Series(y.flatten()).describe()

count    1.000000e+03
mean    -1.136868e-16
std      1.000500e+00
min     -2.066147e+00
25%     -7.383769e-01
50%     -1.693325e-01
75%      5.893935e-01
max      3.434616e+00
dtype: float64

# TODO: Scoring Methods

We define a helper function to save the scores for each model and make a final comparison.

The metrics we will analyse are:
- MSE: Mean Squared Error
- MAE: Mean Absolute Error
- MR: Mean Residual
- **R2 ???????**
- **FAIRNESS QUALCOSA!!! TODO!!**

# PRENDERE DA ONE NOTE !!!!

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error


def mean_residual(y_true, prediction):
    '''Compute the mean residual metric'''
    residuals = (y_true - prediction)
    MR = residuals.mean()
    return MR


def compute_scores(y_true, y_pred):
    '''Compute the following metrics for the given model: MSE, MAE, MR, r2'''
    y_true = y_true.reshape(y_pred.shape)

    MSE = mean_squared_error(y_true, y_pred)
    print(f"MSE: {MSE:.4f}")
    MAE = mean_absolute_error(y_true, y_pred)
    print(f"MAE: {MAE:.4f}")
    MR = mean_residual(y_true, y_pred)
    print(f"MR: {MR:.4f}")
    R2 = r2_score(y_true, y_pred)
    adj_R2 = 1- ((1-R2) * (x.shape[0]-1)/(x.shape[0]-x.shape[1]-1))
    print(f"adj-R2: {adj_R2:.4f}")
    return [MSE, MAE, MR, adj_R2]


def save_scores(model, scores):
    '''Store scores for the given model into a dedicated dataframe for a final comparison across models'''
    MSE, MAE, MR, r2 = scores
    #pd.Series(scores).to_csv('scores/'+model)
    model_names.append(model)
    MSEs.append(MSE)
    MAEs.append(MAE)
    MRs.append(MR)
    r2s.append(r2)


def display_scores():
    scores_df = pd.DataFrame([model_names, MSEs, MAEs, MRs, r2s],
                 index=['method', 'MSE', 'MAE', 'MR', 'adj R-squared']).T
    return scores_df

In [ ]:
model_names, MSEs, MAEs, MRs, r2s = [],[],[],[],[]

# MODELS

# 1. Linear Regression

In [ ]:
import statsmodels.api as sm

In [ ]:
#add constant to predictor variables
x = sm.add_constant(X)
#fit linear regression model
lr = sm.OLS(y, x).fit()

#view model summary
# print(lr.summary())

In [ ]:
X_TEST = sm.add_constant(X_test)
x.shape, X_TEST.shape, X_test.shape, X.shape

((1000, 74), (200, 74), (200, 73), (1000, 73))

In [ ]:
lr_pred = lr.predict(X_TEST)
scores = compute_scores(y_test, lr_pred)
save_scores('LinearRegression', scores)

MSE: 0.2976
MAE: 0.4295
MR: 0.0174
adj-R2: 0.6498

In [93]:
def export_pred(y_pred_std, model, scaler=ss_y):
    ''' TODO: DESC'''

    y_pred = scaler.inverse_transform(np.array(y_pred_std, ndmin=2)).flatten()
    np.savetxt('predictions/'+str(model)+'_pred.csv', y_pred, delimiter=",")

In [94]:
export_pred(lr_pred, 'LinearRegression')

# PREDICTIONS?

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
lr_pred.describe()

count    200.000000
mean      -0.061216
std        0.811683
min       -2.146450
25%       -0.634462
50%       -0.134130
75%        0.564427
max        1.899023
dtype: float64

In [ ]:
# TODO
# revert scaling of pred and y_true
# analysis

In [ ]:
# revert the predictions back to the original scale
lr_pred_original = ss_y.inverse_transform(np.array(lr_pred, ndmin=2))
y_test = ss_y.inverse_transform(np.array(y_test, ndmin=2))

In [ ]:
y_pred = lr_pred_original

In [ ]:
y_test = y_test.flatten()
y_pred = y_pred.flatten()

In [ ]:
lr_pred

0      0.670164
1     -0.418794
2      0.231745
3     -0.378913
4      1.339126
         ...
195    0.713004
196    0.418066
197    0.705828
198    0.393713
199    0.150834
Length: 200, dtype: float64

We now  compare two np.arrays (y_test and y_pred) and identify four cases:
1. y_pred < y_test by at least 0.5
2. y_pred < y_test by no more than 0.5
1. y_pred > y_test by at least 0.5
2. y_pred > y_test by no more than 0.5

In [ ]:
diff = y_pred - y_test

In [ ]:
# Create masks for the four cases
t = 0.5 # threshhold

mask_case1 = (diff <= - t)
mask_case2 = (diff < 0) & (diff > - t)
mask_case3 = (diff >= t)
mask_case4 = (diff > 0) & (diff < t)

In [ ]:
# Apply the masks to identify the cases
case1_indices = np.where(mask_case1)
case2_indices = np.where(mask_case2)
case3_indices = np.where(mask_case3)
case4_indices = np.where(mask_case4)

In [ ]:
len(y_pred)

200

In [ ]:
n_y = len(y_pred)
# Print the indices of data points in each case
print("Case 1 (y_pred < y_test by at least 0.5):", mask_case1.sum()/n_y)
print("Case 2 (y_pred < y_test by no more than 0.5):", sum(mask_case2)/n_y)
print("Case 3 (y_pred > y_test by at least 0.5):", sum(mask_case3)/n_y)
print("Case 4 (y_pred > y_test by no more than 0.5):", sum(mask_case4)/n_y)

Case 1 (y_pred < y_test by at least 0.5): 0.075
Case 2 (y_pred < y_test by no more than 0.5): 0.425
Case 3 (y_pred > y_test by at least 0.5): 0.08
Case 4 (y_pred > y_test by no more than 0.5): 0.42

In [ ]:
def identify_cases(y_test, y_pred, threshold=0.5):
    """
    Identify four cases based on the comparison of y_pred and y_test with a threshold.
    Returns a dictionary containing four lists of indices for each case.
    """
    # Calculate the absolute difference between y_pred and y_test
    diff = y_pred - y_test

    # Create masks for the four cases
    mask_case1 = (diff <= - t)
    mask_case2 = (diff < 0) & (diff > - t)
    mask_case3 = (diff >= t)
    mask_case4 = (diff > 0) & (diff < t)

    # Identify the indices for each case
    case1_indices = np.where(mask_case1)
    case2_indices = np.where(mask_case2)
    case3_indices = np.where(mask_case3)
    case4_indices = np.where(mask_case4)

    # Print the percentages of data points in each case
    n_y = len(y_pred)
    print("Case 1 (y_pred < y_test by at least 0.5):", mask_case1.sum()/n_y)
    print("Case 2 (y_pred < y_test by no more than 0.5):", sum(mask_case2)/n_y)
    print("Case 3 (y_pred > y_test by at least 0.5):", sum(mask_case3)/n_y)
    print("Case 4 (y_pred > y_test by no more than 0.5):", sum(mask_case4)/n_y)

    # Create a dictionary to store the indices for each case
    cases = {
        '1': case1_indices,
        '2': case2_indices,
        '3': case3_indices,
        '4': case4_indices,
    }

    return cases